AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chatbot backend (FastAPI on Lambda + API Gateway)

Parameters:
  QdrantUrl:
    Type: String
  QdrantApiKey:
    Type: String
    NoEcho: true
  CorsOrigin:
    Type: String
    Default: '*'
  OpenAIKey:
    Type: String
    NoEcho: true
  OpenAIModel:
    Type: String
    Default: text-embedding-3-small

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chatbot-backend
      Runtime: python3.10
      Handler: app_lambda.handler
      CodeUri: backend/
      Timeout: 30
      MemorySize: 1024
      Architectures: [x86_64]
      Environment:
        Variables:
          QDRANT_URL: !Ref QdrantUrl
          QDRANT_API_KEY: !Ref QdrantApiKey
          CORS_ORIGIN: !Ref CorsOrigin
          OPENAI_API_KEY: !Ref OpenAIKey
          OPENAI_EMBED_MODEL: !Ref OpenAIModel
          QDRANT_COLLECTION: documents
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "HTTP API base URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
